routes/auth.py
from os import environ
from itsdangerous import URLSafeTimedSerializer, SignatureExpired
from flask import Blueprint, render_template, redirect, url_for, flash, request, jsonify
from flask import session
from werkzeug.security import check_password_hash, generate_password_hash
from flask_login import LoginManager, login_user, logout_user, login_required, current_user
from flask_mail import Mail, Message
import uuid
from models import User, db

auth = Blueprint('auth', __name__,
                 template_folder='../auth')

login_manager = LoginManager()
mail = Mail()


@auth.route('/auth', methods=['GET'])
def index():
    return redirect(url_for('auth.login'))


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        _email = request.form.get('email')
        user = User.query.filter_by(email=_email).first()
        check_password_hash(user.password, request.form.get('password'))
        login_user(user)
        # session['username'] = user.username
        session['uid'] = uuid.uuid4()
        print("%s,%s" % (user.id, session['uid']))
        flash("Hallo, Welcome terug")
        return redirect(url_for('root.werkgever'))
    return render_template('login.html')


@ auth.route('/aanmelden', methods=['GET', 'POST'])
def aanmelden():
    if request.method == 'POST':
        _username = request.form.get('username')
        _email = request.form.get('email')
        if request.form.get('_password') != request.form.get('_repeat_password'):
            flash('wachtwoorden komen niet overeen')
        _password = generate_password_hash(
            request.form.get('password'), method='sha256')
        _repeat = request.form.get('repeat_password')
        user = User(username=_username, email=_email, password=_password)
        db.session.add(user)
        db.session.commit()
        token = generate_email_token(_email)
        print("The token is : {}".format(token))
        return redirect(url_for('auth.authenticate', token=token))
    return render_template('aanmelden.html')


@ auth.route('/authenticate/<token>', methods=['GET', 'POST'])
def authenticate(token):
    return 'authenticate your account {}'.format(token)


@auth.route('/confirm_email')
def confirm_email():
    token = request.args.get('token')
    email = confirm_email_token(token)
    return '{}'.format(email)


@ auth.route('/change-password', methods=['GET', 'POST'])
def change_password():
    return "Change Password"


@ auth.route('/remove-account', methods=['GET', 'POST'])
def remove_account():
    return "Remove account"


@ auth.route('/update-account', methods=['GET', 'POST'])
def update_account():
    return "Update account"


@auth.route('/logout', methods=['GET', 'POST'])
@login_required
def logout():
    logout_user()
    return redirect(url_for('root.index'))


def generate_email_token(email):
    s = URLSafeTimedSerializer(environ.get('SECRET_KEY'))
    salt = environ.get('SECURITY_PASSWORD_SALT')
    return s.dumps(email, salt=salt)


def confirm_email_token(token, expiration=60):
    s = URLSafeTimedSerializer(environ.get('SECRET_KEY'))
    salt = environ.get('SECURITY_PASSWORD_SALT')
    try:
        email = s.loads(token, salt=salt, max_age=expiration)
    except SignatureExpired:
        return "The token has expired"
    return "Confirmed : {}".format(email)


def add_user(user, request):
    '''
    Adding users to the _active_users_list
    '''
    user = user.id
    sid = request.sid

    pass


def remove_user(user):
    '''
    Removing users from the active_users_list
    '''
    pass

templates/partials/flash_message.html
<div>
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <ul class=flashes>
        {% for message in messages %}
        <li>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    {% endwith %}
</div>

templates/partials/footer.html
<footer class="footer mt-auto ">
    <div class="footer_up_div">
        <!-- ############## -->
        <!-- <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom"> -->
        <!-- Left -->

        <!-- Left -->

        <!-- Right -->
        <div class="container-fluid">
            <div class="follow-us d-flex justify-content-center justify-content-lg-between ">
                <div class="">
                    <span>Volg ons op social networks:</span>
                </div>
                <div class="social-icons">

                    <a href="" class="">
                        <i class="fa fa-facebook"></i>
                    </a>

                    <a href="" class="">
                        <i class="fa fa-twitter"></i>
                    </a>

                    <a href="" class="">
                        <i class="fa fa-google"></i>
                    </a>

                    <a href="" class="">
                        <i class="fa fa-instagram"></i>
                    </a>

                    <a href="" class="">
                        <i class="fa fa-linkedin"></i>
                    </a>

                    <a href="" class="">
                        <i class="fa fa-github"></i>
                    </a>
                </div>
            </div>
            <!-- Right -->

            <!-- Section: Social media -->

            <!-- Section: Links  -->
            <div class="contact-info">
                <div class="mt-5">
                    <!-- Grid row -->
                    <div class="row mt-3">
                        <!-- Grid column -->
                        <div class="col-md-3 col-lg-3 col-xl-3 mb-4">
                            <!-- Content -->
                            <h6 class="text-uppercase fw-bold mb-4">
                                <img src="./../../static/assets/favicon.svg" alt="" width="24px" height="24px">
                                Penderosa
                            </h6>
                            <p>
                            <ul class="cus-list">
                                <li class="cus-list-item">Email:hostmaster@penderosa.nl</li>
                                <li class="cus-list-item">Phone:+31 63493992</li>
                                <li class="cus-list-item">Location:Netherlands,Belgium,France</li>
                            </ul>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- ############# -->
    </div>
    <div class="d-flex bg-light py-3">
        <div class=" container text-center sm-text">
            <span class="text-muted">&copy;G.Herdigein voor &TRADE;DinQit ism &reg;Penderosa &dagger;unlimited</span>
        </div>
    </div>
</footer>

templates/partials/navbar.html
<nav class="navbar navbar-dark bg-dark text-white fixed-top">
    <div class="container-fluid">

        <a class="navbar-brand" href="#">
            <img class="img-fluid" src="./../static/assets/favicon.svg" width="32" height="32" alt=""> Penderosa
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar"
            aria-controls="offcanvasDarkNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="offcanvas offcanvas-end bg-black " tabindex="-1" id="offcanvasDarkNavbar"
            aria-labelledby="offcanvasDarkNavbarLabel">
            <div class="offcanvas-header">

                <h5 class="offcanvas-title text-cus-anti-color" id="offcanvasDarkNavbarLabel">
                    <img src="/static/assets/favicon_anti.svg" width="24px" height="24px" alt=""> Penderosa
                </h5>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas"
                    aria-label="Close"></button>
            </div>
            <div class="offcanvas-body">
                <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/"><i class="fa fa-home"></i> Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#"><i class="fa fa-users"></i> Voor Werkgevers</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#"><i class="fa fa-life-ring"></i> Voor Freelancers</a>
                    </li>
                    <!-- <li class="nav-item">
                        <a class="nav-link" href="/over"><i class="fa fa-life-ring"></i> Over Ons</a>
                    </li> -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                            Meer <i class="fa fa-chervron-down"></i>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="/over"><i class="fa fa-linode"></i> Over Ons</a></li>
                            <li><a class="dropdown-item" href="#"><i class="fa fa-balance-scale"></i> Balans</a></li>
                            <li><a class="dropdown-item" href="#"><i class="fa fa-superpowers"></i> Werken bij
                                    Penderosa</a></li>
                        </ul>
                    </li>
                    <div class="my-3 ">
                        {%if not current_user.is_authenticated%}
                        <a href="{{url_for('auth.aanmelden')}}" class="btn btn-sm btn-primary rounded-pill">
                            <i class="fa fa-user"></i> Registreren</a> |

                        <a href="{{url_for('auth.login')}}" class="btn btn-sm btn-danger rounded-pill">
                            <i class="fa fa-lock"></i> Inloggen
                        </a>
                        {%endif%}
                        {%if current_user.is_authenticated %}
                        <a href="{{url_for('auth.logout')}}" class="btn btn-sm btn-danger rounded-pill">
                            <i class="fa fa-unlock"></i> Uitloggen
                        </a>
                        {%endif%}
                    </div>
                    {%if not current_user.is_authenticated%}
                    <div class="justify-content-between sm-text d-none  d-lg-flex">
                        <div class="inline">
                            <a href="{{url_for('auth.login')}}">
                                Wachwoord of Login kwijt
                            </a>
                        </div>
                        <div class="inline">
                            <a href="#">Werkgevers inloggen</a>
                        </div>
                    </div>
                    {%endif%}
            </div>
        </div>
    </div>
</nav>